apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-marketplace.fullname" . }}-secret
  labels:
    {{- include "service-marketplace.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-username: {{ .Values.admin.username | quote }}
  admin-password-hash: {{ .Values.admin.passwordHash | quote }}
  jwt-secret: {{ .Values.jwt.secret | quote }}
  github-client-id: {{ .Values.githubOAuth.clientId | quote }}
  github-client-secret: {{ .Values.githubOAuth.clientSecret | quote }}
