extends:
  - spectral:oas

rules:
  info-contact: error
  info-description: error
  info-license: error
  operation-description: warn
  operation-operationId: error
  operation-tag-defined: error
  operation-success-response: warn
  oas3-api-servers: error
  oas3-valid-media-example: warn
  oas3-valid-schema-example: warn
